s3tests.functional.test_headers.test_object_create_bad_md5_invalid_garbage ... ok
s3tests.functional.test_headers.test_object_create_bad_md5_invalid_short ... ok
s3tests.functional.test_headers.test_object_create_bad_md5_bad ... ok
s3tests.functional.test_headers.test_object_create_bad_md5_empty ... ok
s3tests.functional.test_headers.test_object_create_bad_md5_unreadable ... FAIL
s3tests.functional.test_headers.test_object_create_bad_md5_none ... ok
s3tests.functional.test_headers.test_object_create_bad_expect_empty ... ok
s3tests.functional.test_headers.test_object_create_bad_expect_none ... ok
s3tests.functional.test_headers.test_object_create_bad_contentlength_negative ... ok
s3tests.functional.test_headers.test_object_create_bad_contentlength_none ... ok
s3tests.functional.test_headers.test_object_create_bad_contentlength_unreadable ... ok
s3tests.functional.test_headers.test_object_create_bad_contentlength_mismatch_below ... ok
s3tests.functional.test_headers.test_object_create_bad_contenttype_invalid ... ok
s3tests.functional.test_headers.test_object_create_bad_contenttype_empty ... ok
s3tests.functional.test_headers.test_object_create_bad_contenttype_none ... ok
s3tests.functional.test_headers.test_object_create_bad_ua_empty ... ok
s3tests.functional.test_headers.test_object_create_bad_ua_unreadable ... ERROR
s3tests.functional.test_headers.test_object_create_bad_ua_none ... ok
s3tests.functional.test_headers.test_object_create_bad_authorization_invalid ... ok
s3tests.functional.test_headers.test_object_create_bad_authorization_empty ... ok
s3tests.functional.test_headers.test_object_create_bad_authorization_none ... ok
s3tests.functional.test_headers.test_object_create_bad_authorization_incorrect ... ok
s3tests.functional.test_headers.test_object_create_bad_date_invalid ... ok
s3tests.functional.test_headers.test_object_create_bad_date_empty ... ok
s3tests.functional.test_headers.test_object_create_bad_date_unreadable ... FAIL
s3tests.functional.test_headers.test_object_create_bad_date_none ... ok
s3tests.functional.test_headers.test_object_create_bad_date_before_today ... ok
s3tests.functional.test_headers.test_object_create_bad_date_after_today ... ok
s3tests.functional.test_headers.test_object_create_bad_date_before_epoch ... ok
s3tests.functional.test_headers.test_object_create_bad_date_after_end ... ok
s3tests.functional.test_headers.test_bucket_create_contentlength_none ... ok
s3tests.functional.test_headers.test_object_acl_create_contentlength_none ... ok
s3tests.functional.test_headers.test_bucket_put_bad_canned_acl ... ok
s3tests.functional.test_headers.test_bucket_create_bad_expect_empty ... ok
s3tests.functional.test_headers.test_bucket_create_bad_contentlength_negative ... ok
s3tests.functional.test_headers.test_bucket_create_bad_contentlength_none ... ok
s3tests.functional.test_headers.test_bucket_create_bad_contentlength_unreadable ... ok
s3tests.functional.test_headers.test_bucket_create_bad_ua_empty ... ok
s3tests.functional.test_headers.test_bucket_create_bad_ua_unreadable ... ERROR
s3tests.functional.test_headers.test_bucket_create_bad_ua_none ... ok
s3tests.functional.test_headers.test_bucket_create_bad_authorization_invalid ... ok
s3tests.functional.test_headers.test_bucket_create_bad_authorization_empty ... ok
s3tests.functional.test_headers.test_bucket_create_bad_authorization_none ... ok
s3tests.functional.test_headers.test_bucket_create_bad_date_invalid ... ok
s3tests.functional.test_headers.test_bucket_create_bad_date_empty ... ok
s3tests.functional.test_headers.test_bucket_create_bad_date_unreadable ... FAIL
s3tests.functional.test_headers.test_bucket_create_bad_date_none ... ok
s3tests.functional.test_headers.test_bucket_create_bad_date_before_today ... ok
s3tests.functional.test_headers.test_bucket_create_bad_date_after_today ... ok
s3tests.functional.test_headers.test_bucket_create_bad_date_before_epoch ... ok
s3tests.functional.test_s3.test_bucket_list_empty ... ok
s3tests.functional.test_s3.test_bucket_list_distinct ... ok
s3tests.functional.test_s3.test_bucket_list_many ... ok
s3tests.functional.test_s3.test_bucket_list_delimiter_basic ... ok
s3tests.functional.test_s3.test_bucket_list_delimiter_prefix ... ok
s3tests.functional.test_s3.test_bucket_list_delimiter_alt ... ok
s3tests.functional.test_s3.test_bucket_list_delimiter_unreadable ... ok
s3tests.functional.test_s3.test_bucket_list_delimiter_empty ... ok
s3tests.functional.test_s3.test_bucket_list_delimiter_none ... ok
s3tests.functional.test_s3.test_bucket_list_delimiter_not_exist ... ok
s3tests.functional.test_s3.test_bucket_list_prefix_basic ... ok
s3tests.functional.test_s3.test_bucket_list_prefix_alt ... ok
s3tests.functional.test_s3.test_bucket_list_prefix_empty ... ok
s3tests.functional.test_s3.test_bucket_list_prefix_none ... ok
s3tests.functional.test_s3.test_bucket_list_prefix_not_exist ... ok
s3tests.functional.test_s3.test_bucket_list_prefix_unreadable ... ok
s3tests.functional.test_s3.test_bucket_list_prefix_delimiter_basic ... ok
s3tests.functional.test_s3.test_bucket_list_prefix_delimiter_alt ... ok
s3tests.functional.test_s3.test_bucket_list_prefix_delimiter_prefix_not_exist ... ok
s3tests.functional.test_s3.test_bucket_list_prefix_delimiter_delimiter_not_exist ... ok
s3tests.functional.test_s3.test_bucket_list_prefix_delimiter_prefix_delimiter_not_exist ... ok
s3tests.functional.test_s3.test_bucket_list_maxkeys_one ... ok
s3tests.functional.test_s3.test_bucket_list_maxkeys_zero ... ok
s3tests.functional.test_s3.test_bucket_list_maxkeys_none ... ok
s3tests.functional.test_s3.test_bucket_list_maxkeys_invalid ... ok
s3tests.functional.test_s3.test_bucket_list_marker_none ... ok
s3tests.functional.test_s3.test_bucket_list_marker_empty ... ok
s3tests.functional.test_s3.test_bucket_list_marker_unreadable ... ok
s3tests.functional.test_s3.test_bucket_list_marker_not_in_list ... ok
s3tests.functional.test_s3.test_bucket_list_marker_after_list ... ok
s3tests.functional.test_s3.test_bucket_list_marker_before_list ... ok
s3tests.functional.test_s3.test_bucket_list_return_data ... ok
s3tests.functional.test_s3.test_bucket_list_object_time ... ok
s3tests.functional.test_s3.test_bucket_notexist ... ok
s3tests.functional.test_s3.test_bucket_delete_notexist ... ok
s3tests.functional.test_s3.test_bucket_delete_nonempty ... ok
s3tests.functional.test_s3.test_object_write_to_nonexist_bucket ... ok
s3tests.functional.test_s3.test_bucket_create_delete ... ok
s3tests.functional.test_s3.test_object_read_notexist ... ok
s3tests.functional.test_s3.test_object_create_special_characters ... ok
s3tests.functional.test_s3.test_object_create_unreadable ... ok
s3tests.functional.test_s3.test_multi_object_delete ... ok
s3tests.functional.test_s3.test_object_write_check_etag ... ok
s3tests.functional.test_s3.test_object_write_cache_control ... ok
s3tests.functional.test_s3.test_object_write_expires ... ok
s3tests.functional.test_s3.test_object_write_read_update_read_delete ... ok
s3tests.functional.test_s3.test_object_set_get_metadata_none_to_good ... ok
s3tests.functional.test_s3.test_object_set_get_metadata_none_to_empty ... ok
s3tests.functional.test_s3.test_object_set_get_metadata_overwrite_to_good ... ok
s3tests.functional.test_s3.test_object_set_get_metadata_overwrite_to_empty ... ok
s3tests.functional.test_s3.test_object_set_get_unicode_metadata ... ok
s3tests.functional.test_s3.test_object_set_get_non_utf8_metadata ... ERROR
s3tests.functional.test_s3.test_object_set_get_metadata_empty_to_unreadable_prefix ... ERROR
s3tests.functional.test_s3.test_object_set_get_metadata_empty_to_unreadable_suffix ... ERROR
s3tests.functional.test_s3.test_object_set_get_metadata_empty_to_unreadable_infix ... ERROR
s3tests.functional.test_s3.test_object_set_get_metadata_overwrite_to_unreadable_prefix ... ERROR
s3tests.functional.test_s3.test_object_set_get_metadata_overwrite_to_unreadable_suffix ... ERROR
s3tests.functional.test_s3.test_object_set_get_metadata_overwrite_to_unreadable_infix ... ERROR
s3tests.functional.test_s3.test_object_metadata_replaced_on_put ... ok
s3tests.functional.test_s3.test_object_write_file ... ok
s3tests.functional.test_s3.test_post_object_anonymous_request ... ok
s3tests.functional.test_s3.test_post_object_authenticated_request ... ok
s3tests.functional.test_s3.test_post_object_authenticated_request_bad_access_key ... ok
s3tests.functional.test_s3.test_post_object_set_success_code ... ok
s3tests.functional.test_s3.test_post_object_set_invalid_success_code ... ok
s3tests.functional.test_s3.test_post_object_upload_larger_than_chunk ... ok
s3tests.functional.test_s3.test_post_object_set_key_from_filename ... ok
s3tests.functional.test_s3.test_post_object_ignored_header ... ok
s3tests.functional.test_s3.test_post_object_case_insensitive_condition_fields ... ok
s3tests.functional.test_s3.test_post_object_escaped_field_values ... ok
s3tests.functional.test_s3.test_post_object_success_redirect_action ... ERROR
s3tests.functional.test_s3.test_post_object_invalid_signature ... ok
s3tests.functional.test_s3.test_post_object_invalid_access_key ... ok
s3tests.functional.test_s3.test_post_object_invalid_date_format ... ok
s3tests.functional.test_s3.test_post_object_no_key_specified ... ok
s3tests.functional.test_s3.test_post_object_missing_signature ... ok
s3tests.functional.test_s3.test_post_object_missing_policy_condition ... ok
s3tests.functional.test_s3.test_post_object_user_specified_header ... ok
s3tests.functional.test_s3.test_post_object_request_missing_policy_specified_field ... ok
s3tests.functional.test_s3.test_post_object_condition_is_case_sensitive ... ok
s3tests.functional.test_s3.test_post_object_expires_is_case_sensitive ... ok
s3tests.functional.test_s3.test_post_object_expired_policy ... ok
s3tests.functional.test_s3.test_post_object_invalid_request_field_value ... ok
s3tests.functional.test_s3.test_post_object_missing_expires_condition ... ok
s3tests.functional.test_s3.test_post_object_missing_conditions_list ... ok
s3tests.functional.test_s3.test_post_object_upload_size_limit_exceeded ... ok
s3tests.functional.test_s3.test_post_object_missing_content_length_argument ... ok
s3tests.functional.test_s3.test_post_object_invalid_content_length_argument ... ok
s3tests.functional.test_s3.test_post_object_upload_size_below_minimum ... ok
s3tests.functional.test_s3.test_put_object_ifmatch_good ... ok
s3tests.functional.test_s3.test_put_object_ifmatch_failed ... ok
s3tests.functional.test_s3.test_put_object_ifmatch_overwrite_existed_good ... ok
s3tests.functional.test_s3.test_put_object_ifmatch_nonexisted_failed ... ok
s3tests.functional.test_s3.test_put_object_ifnonmatch_good ... ok
s3tests.functional.test_s3.test_put_object_ifnonmatch_failed ... ok
s3tests.functional.test_s3.test_put_object_ifnonmatch_nonexisted_good ... ok
s3tests.functional.test_s3.test_put_object_ifnonmatch_overwrite_existed_failed ... ok
s3tests.functional.test_s3.test_object_raw_get ... ok
s3tests.functional.test_s3.test_object_raw_get_bucket_gone ... ok
s3tests.functional.test_s3.test_object_delete_key_bucket_gone ... ok
s3tests.functional.test_s3.test_object_raw_get_object_gone ... ok
s3tests.functional.test_s3.test_bucket_head ... ok
s3tests.functional.test_s3.test_bucket_head_extended ... ok
s3tests.functional.test_s3.test_object_raw_get_bucket_acl ... ok
s3tests.functional.test_s3.test_object_raw_get_object_acl ... ok
s3tests.functional.test_s3.test_object_raw_authenticated ... ok
s3tests.functional.test_s3.test_object_raw_authenticated_bucket_acl ... ok
s3tests.functional.test_s3.test_object_raw_authenticated_object_acl ... ok
s3tests.functional.test_s3.test_object_raw_authenticated_bucket_gone ... ok
s3tests.functional.test_s3.test_object_raw_authenticated_object_gone ... ok
s3tests.functional.test_s3.test_object_raw_put ... ok
s3tests.functional.test_s3.test_object_raw_put_write_access ... ok
s3tests.functional.test_s3.test_object_raw_put_authenticated ... ok
s3tests.functional.test_s3.test_object_raw_put_authenticated_expired ... ok
s3tests.functional.test_s3.test_bucket_create_naming_bad_starts_nonalpha ... ok
s3tests.functional.test_s3.test_bucket_create_naming_bad_short_empty ... ok
s3tests.functional.test_s3.test_bucket_create_naming_bad_short_one ... ok
s3tests.functional.test_s3.test_bucket_create_naming_bad_short_two ... ok
s3tests.functional.test_s3.test_bucket_create_naming_bad_long ... ok
s3tests.functional.test_s3.test_bucket_create_naming_good_long_250 ... ok
s3tests.functional.test_s3.test_bucket_create_naming_good_long_251 ... ok
s3tests.functional.test_s3.test_bucket_create_naming_good_long_252 ... ok
s3tests.functional.test_s3.test_bucket_create_naming_good_long_253 ... ok
s3tests.functional.test_s3.test_bucket_create_naming_good_long_254 ... ok
s3tests.functional.test_s3.test_bucket_create_naming_good_long_255 ... ok
s3tests.functional.test_s3.test_bucket_list_long_name ... ok
s3tests.functional.test_s3.test_bucket_create_naming_bad_ip ... ok
s3tests.functional.test_s3.test_bucket_create_naming_bad_punctuation ... ok
s3tests.functional.test_s3.test_bucket_create_naming_dns_underscore ... ok
s3tests.functional.test_s3.test_bucket_create_naming_dns_long ... ok
s3tests.functional.test_s3.test_bucket_create_naming_dns_dash_at_end ... ok
s3tests.functional.test_s3.test_bucket_create_naming_dns_dot_dot ... ok
s3tests.functional.test_s3.test_bucket_create_naming_dns_dot_dash ... ok
s3tests.functional.test_s3.test_bucket_create_naming_dns_dash_dot ... ok
s3tests.functional.test_s3.test_bucket_create_exists ... ok
s3tests.functional.test_s3.test_bucket_get_location ... ok
s3tests.functional.test_s3.test_bucket_create_exists_nonowner ... ok
s3tests.functional.test_s3.test_bucket_delete_nonowner ... ok
s3tests.functional.test_s3.test_bucket_acl_default ... ok
s3tests.functional.test_s3.test_bucket_acl_canned_during_create ... ok
s3tests.functional.test_s3.test_bucket_acl_canned ... ok
s3tests.functional.test_s3.test_bucket_acl_canned_publicreadwrite ... ok
s3tests.functional.test_s3.test_bucket_acl_canned_authenticatedread ... ok
s3tests.functional.test_s3.test_object_acl_default ... ok
s3tests.functional.test_s3.test_object_acl_canned_during_create ... ok
s3tests.functional.test_s3.test_object_acl_canned ... ok
s3tests.functional.test_s3.test_object_acl_canned_publicreadwrite ... ok
s3tests.functional.test_s3.test_object_acl_canned_authenticatedread ... ok
s3tests.functional.test_s3.test_object_acl_canned_bucketownerread ... ok
s3tests.functional.test_s3.test_object_acl_canned_bucketownerfullcontrol ... ok
s3tests.functional.test_s3.test_object_acl_full_control_verify_owner ... ok
s3tests.functional.test_s3.test_object_acl_full_control_verify_attributes ... ok
s3tests.functional.test_s3.test_bucket_acl_canned_private_to_private ... ok
s3tests.functional.test_s3.test_bucket_acl_xml_fullcontrol ... ok
s3tests.functional.test_s3.test_bucket_acl_xml_write ... ok
s3tests.functional.test_s3.test_bucket_acl_xml_writeacp ... ok
s3tests.functional.test_s3.test_bucket_acl_xml_read ... ok
s3tests.functional.test_s3.test_bucket_acl_xml_readacp ... ok
s3tests.functional.test_s3.test_object_acl_xml ... ok
s3tests.functional.test_s3.test_object_acl_xml_write ... ok
s3tests.functional.test_s3.test_object_acl_xml_writeacp ... ok
s3tests.functional.test_s3.test_object_acl_xml_read ... ok
s3tests.functional.test_s3.test_object_acl_xml_readacp ... ok
s3tests.functional.test_s3.test_bucket_acl_grant_userid_fullcontrol ... ok
s3tests.functional.test_s3.test_bucket_acl_grant_userid_read ... ok
s3tests.functional.test_s3.test_bucket_acl_grant_userid_readacp ... ok
s3tests.functional.test_s3.test_bucket_acl_grant_userid_write ... ok
s3tests.functional.test_s3.test_bucket_acl_grant_userid_writeacp ... ok
s3tests.functional.test_s3.test_bucket_acl_grant_nonexist_user ... ok
s3tests.functional.test_s3.test_bucket_acl_no_grants ... ok
s3tests.functional.test_s3.test_object_header_acl_grants ... ok
s3tests.functional.test_s3.test_bucket_header_acl_grants ... ok
s3tests.functional.test_s3.test_bucket_acl_grant_email ... ok
s3tests.functional.test_s3.test_bucket_acl_grant_email_notexist ... ok
s3tests.functional.test_s3.test_bucket_acl_revoke_all ... ok
s3tests.functional.test_s3.test_access_bucket_private_object_private ... ok
s3tests.functional.test_s3.test_access_bucket_private_object_publicread ... ok
s3tests.functional.test_s3.test_access_bucket_private_object_publicreadwrite ... ok
s3tests.functional.test_s3.test_access_bucket_publicread_object_private ... ok
s3tests.functional.test_s3.test_access_bucket_publicread_object_publicread ... ok
s3tests.functional.test_s3.test_access_bucket_publicread_object_publicreadwrite ... ok
s3tests.functional.test_s3.test_access_bucket_publicreadwrite_object_private ... ok
s3tests.functional.test_s3.test_access_bucket_publicreadwrite_object_publicread ... ok
s3tests.functional.test_s3.test_access_bucket_publicreadwrite_object_publicreadwrite ... ok
s3tests.functional.test_s3.test_object_set_valid_acl ... ok
s3tests.functional.test_s3.test_object_giveaway ... ok
s3tests.functional.test_s3.test_buckets_create_then_list ... ok
s3tests.functional.test_s3.test_list_buckets_anonymous ... ok
s3tests.functional.test_s3.test_list_buckets_invalid_auth ... ok
s3tests.functional.test_s3.test_list_buckets_bad_auth ... ok
s3tests.functional.test_s3.test_bucket_create_naming_good_starts_alpha ... ok
s3tests.functional.test_s3.test_bucket_create_naming_good_starts_digit ... ok
s3tests.functional.test_s3.test_bucket_create_naming_good_contains_period ... ok
s3tests.functional.test_s3.test_bucket_create_naming_good_contains_hyphen ... ok
s3tests.functional.test_s3.test_bucket_recreate_not_overriding ... ok
s3tests.functional.test_s3.test_bucket_create_special_key_names ... ok
s3tests.functional.test_s3.test_bucket_list_special_prefix ... ok
s3tests.functional.test_s3.test_object_copy_zero_size ... ok
s3tests.functional.test_s3.test_object_copy_same_bucket ... ok
s3tests.functional.test_s3.test_object_copy_to_itself ... ok
s3tests.functional.test_s3.test_object_copy_to_itself_with_metadata ... ok
s3tests.functional.test_s3.test_object_copy_diff_bucket ... ok
s3tests.functional.test_s3.test_object_copy_not_owned_bucket ... ok
s3tests.functional.test_s3.test_object_copy_not_owned_object_bucket ... ok
s3tests.functional.test_s3.test_object_copy_canned_acl ... ok
s3tests.functional.test_s3.test_object_copy_retaining_metadata ... ok
s3tests.functional.test_s3.test_object_copy_replacing_metadata ... ok
s3tests.functional.test_s3.test_multipart_upload_empty ... ok
s3tests.functional.test_s3.test_multipart_upload_small ... ok
s3tests.functional.test_s3.test_multipart_upload ... ERROR
s3tests.functional.test_s3.test_multipart_upload_resend_part ... ERROR
s3tests.functional.test_s3.test_multipart_upload_multiple_sizes ... ERROR
s3tests.functional.test_s3.test_multipart_upload_size_too_small ... ok
s3tests.functional.test_s3.test_multipart_upload_contents ... ERROR
s3tests.functional.test_s3.test_multipart_upload_overwrite_existing_object ... ERROR
s3tests.functional.test_s3.test_abort_multipart_upload ... ERROR
s3tests.functional.test_s3.test_abort_multipart_upload_not_found ... ok
s3tests.functional.test_s3.test_list_multipart_upload ... ERROR
s3tests.functional.test_s3.test_multipart_upload_missing_part ... ok
s3tests.functional.test_s3.test_multipart_upload_incorrect_etag ... ok
s3tests.functional.test_s3.test_100_continue ... ERROR
s3tests.functional.test_s3.test_bucket_acls_changes_persistent ... ok
s3tests.functional.test_s3.test_stress_bucket_acls_changes ... ok
s3tests.functional.test_s3.test_set_cors ... ok
s3tests.functional.test_s3.test_cors_origin_response ... ok
s3tests.functional.test_s3.test_atomic_read_1mb ... ok
s3tests.functional.test_s3.test_atomic_read_4mb ... ok
s3tests.functional.test_s3.test_atomic_read_8mb ... ERROR
s3tests.functional.test_s3.test_atomic_write_1mb ... ok
s3tests.functional.test_s3.test_atomic_write_4mb ... ok
s3tests.functional.test_s3.test_atomic_write_8mb ... ERROR
s3tests.functional.test_s3.test_atomic_dual_write_1mb ... ok
s3tests.functional.test_s3.test_atomic_dual_write_4mb ... ok
s3tests.functional.test_s3.test_atomic_dual_write_8mb ... ERROR
s3tests.functional.test_s3.test_atomic_conditional_write_1mb ... ok
s3tests.functional.test_s3.test_atomic_dual_conditional_write_1mb ... ok
s3tests.functional.test_s3.test_atomic_write_bucket_gone ... ok
s3tests.functional.test_s3.test_ranged_request_response_code ... ok
s3tests.functional.test_s3.test_ranged_request_skip_leading_bytes_response_code ... ok
s3tests.functional.test_s3.test_ranged_request_return_trailing_bytes_response_code ... ok
s3tests.functional.test_s3.test_ranged_request_invalid_range ... ok
s3tests.functional.test_s3.check_can_test_multiregion ... SKIP
s3tests.functional.test_s3.test_region_bucket_create_secondary_access_remove_master ... SKIP
s3tests.functional.test_s3.test_region_bucket_create_master_access_remove_secondary ... SKIP
s3tests.functional.test_s3.test_region_copy_object ... SKIP
s3tests.functional.test_s3.test_versioning_bucket_create_suspend ... ok
s3tests.functional.test_s3.test_versioning_obj_create_read_remove ... ok
s3tests.functional.test_s3.test_versioning_obj_create_read_remove_head ... ok
s3tests.functional.test_s3.test_versioning_obj_suspend_versions ... ok
s3tests.functional.test_s3.test_versioning_obj_suspend_versions_simple ... ok
s3tests.functional.test_s3.test_versioning_obj_create_versions_remove_all ... ok
s3tests.functional.test_s3.test_versioning_obj_create_versions_remove_special_names ... ok
s3tests.functional.test_s3.test_versioning_obj_create_overwrite_multipart ... ERROR
s3tests.functional.test_s3.test_versioning_obj_list_marker ... ok
s3tests.functional.test_s3.test_versioning_copy_obj_version ... ok
s3tests.functional.test_s3.test_versioning_multi_object_delete ... ok
s3tests.functional.test_s3.test_versioning_multi_object_delete_with_marker ... ok
s3tests.functional.test_s3.test_versioning_multi_object_delete_with_marker_create ... ok
s3tests.functional.test_s3.test_versioned_object_acl ... ok
s3tests.functional.test_s3.test_versioned_concurrent_object_create_concurrent_remove ... ok
s3tests.functional.test_s3.test_versioned_concurrent_object_create_and_remove ... ok
s3tests.functional.test_utils.test_generate ... ok
s3tests.fuzz.test.test_fuzzer.test_load_graph ... ok
s3tests.fuzz.test.test_fuzzer.test_descend_leaf_node ... ok
s3tests.fuzz.test.test_fuzzer.test_descend_node ... ok
s3tests.fuzz.test.test_fuzzer.test_descend_bad_node ... ok
s3tests.fuzz.test.test_fuzzer.test_descend_nonexistant_child ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_random_printable ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_random_binary ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_random_printable_no_whitespace ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_random_binary_no_whitespace ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_random_no_args ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_random_no_charset ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_random_exact_length ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_random_bad_charset ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_random_missing_length ... ok
s3tests.fuzz.test.test_fuzzer.test_assemble_decision ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_escape ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_indirect ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_indirect_double ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_recursive ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_recursive_mutual ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_recursive_not_too_eager ... ok
s3tests.fuzz.test.test_fuzzer.test_make_choice_unweighted_with_space ... ok
s3tests.fuzz.test.test_fuzzer.test_weighted_choices ... ok
s3tests.fuzz.test.test_fuzzer.test_null_choices ... ok
s3tests.fuzz.test.test_fuzzer.test_weighted_null_choices ... ok
s3tests.fuzz.test.test_fuzzer.test_null_child ... ok
s3tests.fuzz.test.test_fuzzer.test_weighted_set ... ok
s3tests.fuzz.test.test_fuzzer.test_header_presence ... ok
s3tests.fuzz.test.test_fuzzer.test_duplicate_header ... ok
s3tests.fuzz.test.test_fuzzer.test_expand_headers ... ok
test_realistic.TestFileValidator.test_new_file_is_valid ... ok
test_realistic.TestFileValidator.test_new_file_is_valid_on_several_calls ... ok
test_realistic.TestFileValidator.test_new_file_is_valid_when_size_is_1 ... ok
test_realistic.TestFiles.test_random_file_valid ... ok

======================================================================
ERROR: s3tests.functional.test_headers.test_object_create_bad_ua_unreadable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_headers.py", line 451, in test_object_create_bad_ua_unreadable
    key.set_contents_from_string('bar')
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1426, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-17/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-17/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-17/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:19:39 GMT
/rzarzynski-idqx3zorqinxhcpn6a-17/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:VYmOX1MmJIw/cPqvOePELRd2y0o=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:19:39 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:VYmOX1MmJIw/cPqvOePELRd2y0o=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:19:39 GMT
/rzarzynski-idqx3zorqinxhcpn6a-17/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:VYmOX1MmJIw/cPqvOePELRd2y0o=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:19:39 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:VYmOX1MmJIw/cPqvOePELRd2y0o=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:19:40 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000021-0057f57c7b-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-17/foo
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-17/foo
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-17/foo
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '3', 'Content-MD5': u'N7UdGUp1E+RbVvZSTy1R8g==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:19:40 GMT
/rzarzynski-idqx3zorqinxhcpn6a-17/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:2c5g2TLuFelaeQDhcPb5mWpc/Eo=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:19:40 GMT', 'User-Agent': '\x07', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:2c5g2TLuFelaeQDhcPb5mWpc/Eo=', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g=='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:19:40 GMT
/rzarzynski-idqx3zorqinxhcpn6a-17/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:2c5g2TLuFelaeQDhcPb5mWpc/Eo=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:19:40 GMT', 'User-Agent': '\x07', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:2c5g2TLuFelaeQDhcPb5mWpc/Eo=', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g=='}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_headers.test_bucket_create_bad_ua_unreadable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_headers.py", line 805, in test_bucket_create_bad_ua_unreadable
    bucket = get_new_bucket()
  File "/work/s3-tests/s3tests/functional/__init__.py", line 393, in get_new_bucket
    bucket = connection.create_bucket(name, location=target.conf.api_name, headers=headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 621, in create_bucket
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-39/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-39/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-39/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:19:54 GMT
/rzarzynski-idqx3zorqinxhcpn6a-39/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:ZsMTKs02xqQtkTfos0ZSLt0Drjc=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:19:54 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:ZsMTKs02xqQtkTfos0ZSLt0Drjc=', 'User-Agent': '\x07'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:19:54 GMT
/rzarzynski-idqx3zorqinxhcpn6a-39/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:ZsMTKs02xqQtkTfos0ZSLt0Drjc=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:19:54 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:ZsMTKs02xqQtkTfos0ZSLt0Drjc=', 'User-Agent': '\x07'}
boto: DEBUG: Response headers: [('content-length', '0')]
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_object_set_get_non_utf8_metadata
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1028, in test_object_set_get_non_utf8_metadata
    key.set_contents_from_string('bar')
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1426, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-99/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-99/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-99/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:22:27 GMT
/rzarzynski-idqx3zorqinxhcpn6a-99/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:mWeMvGgJpp8NRgvb2kHtTE5remg=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:22:27 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:mWeMvGgJpp8NRgvb2kHtTE5remg=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:22:27 GMT
/rzarzynski-idqx3zorqinxhcpn6a-99/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:mWeMvGgJpp8NRgvb2kHtTE5remg=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:22:27 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:mWeMvGgJpp8NRgvb2kHtTE5remg=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:22:28 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000160-0057f57d24-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-99/foo
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-99/foo
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-99/foo
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Content-Type': 'application/octet-stream', 'Content-MD5': u'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': '\x04mymeta', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:28 GMT
x-amz-meta-meta1:mymeta
/rzarzynski-idqx3zorqinxhcpn6a-99/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:SrxM5Q7hiOeZda4oKVCmJiEUsxA=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:28 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': '\x04mymeta', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:SrxM5Q7hiOeZda4oKVCmJiEUsxA=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:28 GMT
x-amz-meta-meta1:mymeta
/rzarzynski-idqx3zorqinxhcpn6a-99/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:SrxM5Q7hiOeZda4oKVCmJiEUsxA=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:28 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': '\x04mymeta', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:SrxM5Q7hiOeZda4oKVCmJiEUsxA=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_object_set_get_metadata_empty_to_unreadable_prefix
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1053, in test_object_set_get_metadata_empty_to_unreadable_prefix
    got = _set_get_metadata_unreadable(metadata)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1041, in _set_get_metadata_unreadable
    got = _set_get_metadata(metadata, bucket)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 956, in _set_get_metadata
    key.set_contents_from_string('bar')
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1426, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-100/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-100/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-100/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:22:29 GMT
/rzarzynski-idqx3zorqinxhcpn6a-100/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:3giUzJjdCRGX7qtjJQi1ibijDdE=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:22:29 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:3giUzJjdCRGX7qtjJQi1ibijDdE=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:22:29 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000161-0057f57d25-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-100/foo
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-100/foo
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-100/foo
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Content-Type': 'application/octet-stream', 'Content-MD5': u'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': '\x04w', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:29 GMT
x-amz-meta-meta1:w
/rzarzynski-idqx3zorqinxhcpn6a-100/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:PE/RhGI3QolEqSkcPDLNriZTvlg=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:29 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': '\x04w', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:PE/RhGI3QolEqSkcPDLNriZTvlg=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:29 GMT
x-amz-meta-meta1:w
/rzarzynski-idqx3zorqinxhcpn6a-100/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:PE/RhGI3QolEqSkcPDLNriZTvlg=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:29 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': '\x04w', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:PE/RhGI3QolEqSkcPDLNriZTvlg=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_object_set_get_metadata_empty_to_unreadable_suffix
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1064, in test_object_set_get_metadata_empty_to_unreadable_suffix
    got = _set_get_metadata_unreadable(metadata)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1041, in _set_get_metadata_unreadable
    got = _set_get_metadata(metadata, bucket)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 956, in _set_get_metadata
    key.set_contents_from_string('bar')
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1426, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-101/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-101/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-101/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:22:30 GMT
/rzarzynski-idqx3zorqinxhcpn6a-101/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:yJPzGWxmf1wwbiEv/wgNzQiIEZ4=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:22:30 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:yJPzGWxmf1wwbiEv/wgNzQiIEZ4=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:22:30 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000162-0057f57d26-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-101/foo
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-101/foo
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-101/foo
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Content-Type': 'application/octet-stream', 'Content-MD5': u'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': 'h\x04', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:30 GMT
x-amz-meta-meta1:h
/rzarzynski-idqx3zorqinxhcpn6a-101/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:+J+0IWXW1MnEi5n84qXPGLA6iso=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:30 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': 'h\x04', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:+J+0IWXW1MnEi5n84qXPGLA6iso=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:30 GMT
x-amz-meta-meta1:h
/rzarzynski-idqx3zorqinxhcpn6a-101/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:+J+0IWXW1MnEi5n84qXPGLA6iso=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:30 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': 'h\x04', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:+J+0IWXW1MnEi5n84qXPGLA6iso=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_object_set_get_metadata_empty_to_unreadable_infix
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1074, in test_object_set_get_metadata_empty_to_unreadable_infix
    got = _set_get_metadata_unreadable(metadata)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1041, in _set_get_metadata_unreadable
    got = _set_get_metadata(metadata, bucket)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 956, in _set_get_metadata
    key.set_contents_from_string('bar')
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1426, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-102/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-102/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-102/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:22:30 GMT
/rzarzynski-idqx3zorqinxhcpn6a-102/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:JQwgmvNv45rvSBzQH6BfwyiQr9M=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:22:30 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:JQwgmvNv45rvSBzQH6BfwyiQr9M=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:22:30 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000163-0057f57d26-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-102/foo
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-102/foo
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-102/foo
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Content-Type': 'application/octet-stream', 'Content-MD5': u'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': 'h\x04w', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:30 GMT
x-amz-meta-meta1:hw
/rzarzynski-idqx3zorqinxhcpn6a-102/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:tx25tAFLQ0eaJEBg43iKw5Tvvno=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:30 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': 'h\x04w', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:tx25tAFLQ0eaJEBg43iKw5Tvvno=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:30 GMT
x-amz-meta-meta1:hw
/rzarzynski-idqx3zorqinxhcpn6a-102/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:tx25tAFLQ0eaJEBg43iKw5Tvvno=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:30 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': 'h\x04w', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:tx25tAFLQ0eaJEBg43iKw5Tvvno=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_object_set_get_metadata_overwrite_to_unreadable_prefix
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1085, in test_object_set_get_metadata_overwrite_to_unreadable_prefix
    got = _set_get_metadata_unreadable(metadata)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1041, in _set_get_metadata_unreadable
    got = _set_get_metadata(metadata, bucket)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 956, in _set_get_metadata
    key.set_contents_from_string('bar')
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1426, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-103/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-103/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-103/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:22:31 GMT
/rzarzynski-idqx3zorqinxhcpn6a-103/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:83RwOvZPwgw7WiCZOXgMPztLTC0=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:22:31 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:83RwOvZPwgw7WiCZOXgMPztLTC0=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:22:31 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000164-0057f57d27-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-103/foo
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-103/foo
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-103/foo
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Content-Type': 'application/octet-stream', 'Content-MD5': u'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': '\x04w', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:31 GMT
x-amz-meta-meta1:w
/rzarzynski-idqx3zorqinxhcpn6a-103/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:awGnhMeGj+WFUwUdsmdkBZShSPQ=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:31 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': '\x04w', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:awGnhMeGj+WFUwUdsmdkBZShSPQ=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:31 GMT
x-amz-meta-meta1:w
/rzarzynski-idqx3zorqinxhcpn6a-103/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:awGnhMeGj+WFUwUdsmdkBZShSPQ=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:31 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': '\x04w', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:awGnhMeGj+WFUwUdsmdkBZShSPQ=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered UnknownProtocol exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:31 GMT
x-amz-meta-meta1:w
/rzarzynski-idqx3zorqinxhcpn6a-103/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:awGnhMeGj+WFUwUdsmdkBZShSPQ=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:31 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': '\x04w', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:awGnhMeGj+WFUwUdsmdkBZShSPQ=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_object_set_get_metadata_overwrite_to_unreadable_suffix
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1099, in test_object_set_get_metadata_overwrite_to_unreadable_suffix
    got = _set_get_metadata_unreadable(metadata)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1041, in _set_get_metadata_unreadable
    got = _set_get_metadata(metadata, bucket)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 956, in _set_get_metadata
    key.set_contents_from_string('bar')
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1426, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-104/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-104/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-104/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:22:32 GMT
/rzarzynski-idqx3zorqinxhcpn6a-104/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:sq8PL5SYSCiUZ35W8crShZH/LUs=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:22:32 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:sq8PL5SYSCiUZ35W8crShZH/LUs=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:22:32 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000165-0057f57d28-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-104/foo
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-104/foo
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-104/foo
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Content-Type': 'application/octet-stream', 'Content-MD5': u'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': 'h\x04', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:32 GMT
x-amz-meta-meta1:h
/rzarzynski-idqx3zorqinxhcpn6a-104/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:DCk91gke3S692um6EOUIA2MmuNE=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:32 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': 'h\x04', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:DCk91gke3S692um6EOUIA2MmuNE=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:32 GMT
x-amz-meta-meta1:h
/rzarzynski-idqx3zorqinxhcpn6a-104/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:DCk91gke3S692um6EOUIA2MmuNE=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:32 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': 'h\x04', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:DCk91gke3S692um6EOUIA2MmuNE=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_object_set_get_metadata_overwrite_to_unreadable_infix
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1112, in test_object_set_get_metadata_overwrite_to_unreadable_infix
    got = _set_get_metadata_unreadable(metadata)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1041, in _set_get_metadata_unreadable
    got = _set_get_metadata(metadata, bucket)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 956, in _set_get_metadata
    key.set_contents_from_string('bar')
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1426, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-105/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-105/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-105/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:22:32 GMT
/rzarzynski-idqx3zorqinxhcpn6a-105/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:2SsMELoBf60GmBHi6u6KQeSwAF0=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:22:32 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:2SsMELoBf60GmBHi6u6KQeSwAF0=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:22:33 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000166-0057f57d28-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-105/foo
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-105/foo
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-105/foo
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Content-Type': 'application/octet-stream', 'Content-MD5': u'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': 'h\x04w', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:33 GMT
x-amz-meta-meta1:hw
/rzarzynski-idqx3zorqinxhcpn6a-105/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:cYzABtV6BD0T9P/H6ierHi9Igno=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:33 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': 'h\x04w', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:cYzABtV6BD0T9P/H6ierHi9Igno=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream
Wed, 05 Oct 2016 22:22:33 GMT
x-amz-meta-meta1:hw
/rzarzynski-idqx3zorqinxhcpn6a-105/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:cYzABtV6BD0T9P/H6ierHi9Igno=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:22:33 GMT', 'Content-Type': 'application/octet-stream', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g==', 'x-amz-meta-meta1': 'h\x04w', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:cYzABtV6BD0T9P/H6ierHi9Igno=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_post_object_success_redirect_action
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 1513, in test_post_object_success_redirect_action
    r = requests.post(url, files = payload)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/requests/api.py", line 98, in post
    return request('post', url, data=data, **kwargs)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/requests/safe_mode.py", line 39, in wrapped
    return function(method, url, **kwargs)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/requests/api.py", line 51, in request
    return session.request(method=method, url=url, **kwargs)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/requests/sessions.py", line 252, in request
    r.send(prefetch=prefetch)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/requests/models.py", line 639, in send
    self._build_response(r)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/requests/models.py", line 308, in _build_response
    request.send()
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/requests/models.py", line 625, in send
    raise ConnectionError(sockerr)
ConnectionError: [Errno 104] Connection reset by peer
-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-118/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-118/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-118/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:22:50 GMT
/rzarzynski-idqx3zorqinxhcpn6a-118/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:EDnOrfiPyZNMgYoJ8s8XhpC8gjg=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:22:50 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:EDnOrfiPyZNMgYoJ8s8XhpC8gjg=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:22:50 GMT
/rzarzynski-idqx3zorqinxhcpn6a-118/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:EDnOrfiPyZNMgYoJ8s8XhpC8gjg=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:22:50 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:EDnOrfiPyZNMgYoJ8s8XhpC8gjg=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:22:51 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000190-0057f57d3b-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-118/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-118/
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-118/?acl
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-118/?acl
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-118/?acl
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'x-amz-acl': 'public-read'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:22:51 GMT
x-amz-acl:public-read
/rzarzynski-idqx3zorqinxhcpn6a-118/?acl
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:UGBlzcAidf6zCYG08olsitzTJ28=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:22:51 GMT', 'Content-Length': '0', 'x-amz-acl': 'public-read', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:UGBlzcAidf6zCYG08olsitzTJ28=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:22:51 GMT
x-amz-acl:public-read
/rzarzynski-idqx3zorqinxhcpn6a-118/?acl
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:UGBlzcAidf6zCYG08olsitzTJ28=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:22:51 GMT', 'Content-Length': '0', 'x-amz-acl': 'public-read', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:UGBlzcAidf6zCYG08olsitzTJ28=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:22:52 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000191-0057f57d3c-1021-default'), ('content-type', 'application/xml')]
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /rzarzynski-idqx3zorqinxhcpn6a-118 HTTP/1.1" 303 0
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_multipart_upload
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4665, in test_multipart_upload
    (upload, data) = _multipart_upload(bucket, key, objlen, headers={'Content-Type': content_type}, metadata={'foo': 'bar'})
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4612, in _multipart_upload
    transfer_part(bucket, upload.id, upload.key_name, i, part)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4580, in transfer_part
    mp.upload_part_from_file(part_out, i+1)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-245/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-245/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-245/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:27:28 GMT
/rzarzynski-idqx3zorqinxhcpn6a-245/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:KPWe6I7faDIGJL/R+axUOTh3uDM=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:28 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:KPWe6I7faDIGJL/R+axUOTh3uDM=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:27:28 GMT
/rzarzynski-idqx3zorqinxhcpn6a-245/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:KPWe6I7faDIGJL/R+axUOTh3uDM=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:28 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:KPWe6I7faDIGJL/R+axUOTh3uDM=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:28 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx0000000000000000003f3-0057f57e50-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart?uploads
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart?uploads
boto: DEBUG: Method: POST
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart?uploads
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Type': 'text/bla', 'x-amz-meta-foo': 'bar'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST

text/bla
Wed, 05 Oct 2016 22:27:28 GMT
x-amz-meta-foo:bar
/rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:dHsCx+DNGTkJ7aec8ldQkcALJn0=
boto: DEBUG: Final headers: {'Content-Length': '0', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'x-amz-meta-foo': 'bar', 'Date': 'Wed, 05 Oct 2016 22:27:28 GMT', 'Content-Type': 'text/bla', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:dHsCx+DNGTkJ7aec8ldQkcALJn0='}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST

text/bla
Wed, 05 Oct 2016 22:27:28 GMT
x-amz-meta-foo:bar
/rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:dHsCx+DNGTkJ7aec8ldQkcALJn0=
boto: DEBUG: Final headers: {'Content-Length': '0', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'x-amz-meta-foo': 'bar', 'Date': 'Wed, 05 Oct 2016 22:27:28 GMT', 'Content-Type': 'text/bla', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:dHsCx+DNGTkJ7aec8ldQkcALJn0='}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:29 GMT'), ('content-length', '275'), ('x-amz-request-id', 'tx0000000000000000003f4-0057f57e51-1021-default'), ('content-type', 'application/xml')]
boto: DEBUG: <?xml version="1.0" encoding="UTF-8"?><InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>rzarzynski-idqx3zorqinxhcpn6a-245</Bucket><Key>mymultipart</Key><UploadId>2~ImnEDzlm0rjd8OGc9Mwm7FrZFJeCoCT</UploadId></InitiateMultipartUploadResult>
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart?uploadId=2~ImnEDzlm0rjd8OGc9Mwm7FrZFJeCoCT&partNumber=1
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart?uploadId=2~ImnEDzlm0rjd8OGc9Mwm7FrZFJeCoCT&partNumber=1
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart?uploadId=2~ImnEDzlm0rjd8OGc9Mwm7FrZFJeCoCT&partNumber=1
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '5242880', 'Content-MD5': u'ygIUOxNSqlcBzxCwQE7oQg==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
ygIUOxNSqlcBzxCwQE7oQg==
application/octet-stream
Wed, 05 Oct 2016 22:27:29 GMT
/rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart?partNumber=1&uploadId=2~ImnEDzlm0rjd8OGc9Mwm7FrZFJeCoCT
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:stK2yuVqcDsZXOxm49fTIjymX9Q=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'ygIUOxNSqlcBzxCwQE7oQg==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:29 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:stK2yuVqcDsZXOxm49fTIjymX9Q='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
ygIUOxNSqlcBzxCwQE7oQg==
application/octet-stream
Wed, 05 Oct 2016 22:27:29 GMT
/rzarzynski-idqx3zorqinxhcpn6a-245/mymultipart?partNumber=1&uploadId=2~ImnEDzlm0rjd8OGc9Mwm7FrZFJeCoCT
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:stK2yuVqcDsZXOxm49fTIjymX9Q=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'ygIUOxNSqlcBzxCwQE7oQg==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:29 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:stK2yuVqcDsZXOxm49fTIjymX9Q='}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_multipart_upload_resend_part
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4711, in test_multipart_upload_resend_part
    _check_upload_multipart_resend(bucket, key, objlen, [0])
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4685, in _check_upload_multipart_resend
    (upload, data) = _multipart_upload(bucket, key, objlen, headers={'Content-Type': content_type}, metadata={'foo': 'bar'}, resend_parts=resend_parts)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4612, in _multipart_upload
    transfer_part(bucket, upload.id, upload.key_name, i, part)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4580, in transfer_part
    mp.upload_part_from_file(part_out, i+1)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-246/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-246/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-246/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:27:29 GMT
/rzarzynski-idqx3zorqinxhcpn6a-246/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:uvLXQh/J0PzxlwifFtij+tNoMZ4=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:29 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:uvLXQh/J0PzxlwifFtij+tNoMZ4=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:30 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx0000000000000000003f5-0057f57e51-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart?uploads
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart?uploads
boto: DEBUG: Method: POST
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart?uploads
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Type': 'text/bla', 'x-amz-meta-foo': 'bar'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST

text/bla
Wed, 05 Oct 2016 22:27:30 GMT
x-amz-meta-foo:bar
/rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:0UmimzkRiukzGCvfYIEozierwyI=
boto: DEBUG: Final headers: {'Content-Length': '0', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'x-amz-meta-foo': 'bar', 'Date': 'Wed, 05 Oct 2016 22:27:30 GMT', 'Content-Type': 'text/bla', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:0UmimzkRiukzGCvfYIEozierwyI='}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST

text/bla
Wed, 05 Oct 2016 22:27:30 GMT
x-amz-meta-foo:bar
/rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:0UmimzkRiukzGCvfYIEozierwyI=
boto: DEBUG: Final headers: {'Content-Length': '0', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'x-amz-meta-foo': 'bar', 'Date': 'Wed, 05 Oct 2016 22:27:30 GMT', 'Content-Type': 'text/bla', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:0UmimzkRiukzGCvfYIEozierwyI='}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:30 GMT'), ('content-length', '275'), ('x-amz-request-id', 'tx0000000000000000003f6-0057f57e52-1021-default'), ('content-type', 'application/xml')]
boto: DEBUG: <?xml version="1.0" encoding="UTF-8"?><InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>rzarzynski-idqx3zorqinxhcpn6a-246</Bucket><Key>mymultipart</Key><UploadId>2~9wuvw7SDt48DBRgVvI0SzT3es5v2XwV</UploadId></InitiateMultipartUploadResult>
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart?uploadId=2~9wuvw7SDt48DBRgVvI0SzT3es5v2XwV&partNumber=1
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart?uploadId=2~9wuvw7SDt48DBRgVvI0SzT3es5v2XwV&partNumber=1
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart?uploadId=2~9wuvw7SDt48DBRgVvI0SzT3es5v2XwV&partNumber=1
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '5242880', 'Content-MD5': u'vvzyAhIwIgC8l7au+gGkoA==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
vvzyAhIwIgC8l7au+gGkoA==
application/octet-stream
Wed, 05 Oct 2016 22:27:30 GMT
/rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart?partNumber=1&uploadId=2~9wuvw7SDt48DBRgVvI0SzT3es5v2XwV
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:XitjMFrbu/MFLKRHFpPcnUZCZXQ=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'vvzyAhIwIgC8l7au+gGkoA==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:30 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:XitjMFrbu/MFLKRHFpPcnUZCZXQ='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
vvzyAhIwIgC8l7au+gGkoA==
application/octet-stream
Wed, 05 Oct 2016 22:27:30 GMT
/rzarzynski-idqx3zorqinxhcpn6a-246/mymultipart?partNumber=1&uploadId=2~9wuvw7SDt48DBRgVvI0SzT3es5v2XwV
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:XitjMFrbu/MFLKRHFpPcnUZCZXQ=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'vvzyAhIwIgC8l7au+gGkoA==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:30 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:XitjMFrbu/MFLKRHFpPcnUZCZXQ='}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_multipart_upload_multiple_sizes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4721, in test_multipart_upload_multiple_sizes
    (upload, data) = _multipart_upload(bucket, key, 5 * 1024 * 1024)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4612, in _multipart_upload
    transfer_part(bucket, upload.id, upload.key_name, i, part)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4580, in transfer_part
    mp.upload_part_from_file(part_out, i+1)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-247/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-247/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-247/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:27:31 GMT
/rzarzynski-idqx3zorqinxhcpn6a-247/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:LJu7Tntrbk2bEncWKzTfzje1c9Y=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:31 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:LJu7Tntrbk2bEncWKzTfzje1c9Y=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:31 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx0000000000000000003f7-0057f57e53-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart?uploads
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart?uploads
boto: DEBUG: Method: POST
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart?uploads
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST


Wed, 05 Oct 2016 22:27:31 GMT
/rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:lz94RwxXzUl9dloiJPi67MQJlL8=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:31 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:lz94RwxXzUl9dloiJPi67MQJlL8=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST


Wed, 05 Oct 2016 22:27:31 GMT
/rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:lz94RwxXzUl9dloiJPi67MQJlL8=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:31 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:lz94RwxXzUl9dloiJPi67MQJlL8=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:31 GMT'), ('content-length', '275'), ('x-amz-request-id', 'tx0000000000000000003f8-0057f57e53-1021-default'), ('content-type', 'application/xml')]
boto: DEBUG: <?xml version="1.0" encoding="UTF-8"?><InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>rzarzynski-idqx3zorqinxhcpn6a-247</Bucket><Key>mymultipart</Key><UploadId>2~cD0KlCfhE1-Ck-4VRVh2SftcdbDjGRe</UploadId></InitiateMultipartUploadResult>
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart?uploadId=2~cD0KlCfhE1-Ck-4VRVh2SftcdbDjGRe&partNumber=1
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart?uploadId=2~cD0KlCfhE1-Ck-4VRVh2SftcdbDjGRe&partNumber=1
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart?uploadId=2~cD0KlCfhE1-Ck-4VRVh2SftcdbDjGRe&partNumber=1
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '5242880', 'Content-MD5': u'W1BErPxEwgTIixixQhmfqA==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
W1BErPxEwgTIixixQhmfqA==
application/octet-stream
Wed, 05 Oct 2016 22:27:31 GMT
/rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart?partNumber=1&uploadId=2~cD0KlCfhE1-Ck-4VRVh2SftcdbDjGRe
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:+UjDb/8zXRs95I9bZVZ3RTVgedM=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'W1BErPxEwgTIixixQhmfqA==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:31 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:+UjDb/8zXRs95I9bZVZ3RTVgedM='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
W1BErPxEwgTIixixQhmfqA==
application/octet-stream
Wed, 05 Oct 2016 22:27:31 GMT
/rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart?partNumber=1&uploadId=2~cD0KlCfhE1-Ck-4VRVh2SftcdbDjGRe
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:+UjDb/8zXRs95I9bZVZ3RTVgedM=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'W1BErPxEwgTIixixQhmfqA==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:31 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:+UjDb/8zXRs95I9bZVZ3RTVgedM='}
boto: DEBUG: encountered UnknownProtocol exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
W1BErPxEwgTIixixQhmfqA==
application/octet-stream
Wed, 05 Oct 2016 22:27:31 GMT
/rzarzynski-idqx3zorqinxhcpn6a-247/mymultipart?partNumber=1&uploadId=2~cD0KlCfhE1-Ck-4VRVh2SftcdbDjGRe
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:+UjDb/8zXRs95I9bZVZ3RTVgedM=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'W1BErPxEwgTIixixQhmfqA==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:31 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:+UjDb/8zXRs95I9bZVZ3RTVgedM='}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_multipart_upload_contents
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4780, in test_multipart_upload_contents
    _do_test_multipart_upload_contents(get_new_bucket(), 'mymultipart', 3)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4758, in _do_test_multipart_upload_contents
    mp.upload_part_from_file(StringIO(payload), i+1)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-249/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-249/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-249/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:27:41 GMT
/rzarzynski-idqx3zorqinxhcpn6a-249/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:8S9jWsMMMqNMIwNAUon6URqI+O4=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:41 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:8S9jWsMMMqNMIwNAUon6URqI+O4=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:27:41 GMT
/rzarzynski-idqx3zorqinxhcpn6a-249/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:8S9jWsMMMqNMIwNAUon6URqI+O4=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:41 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:8S9jWsMMMqNMIwNAUon6URqI+O4=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:42 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000407-0057f57e5e-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart?uploads
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart?uploads
boto: DEBUG: Method: POST
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart?uploads
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST


Wed, 05 Oct 2016 22:27:42 GMT
/rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:lhOQ51Hc3MfoJXoMmosFIUQLaM8=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:42 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:lhOQ51Hc3MfoJXoMmosFIUQLaM8=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST


Wed, 05 Oct 2016 22:27:42 GMT
/rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:lhOQ51Hc3MfoJXoMmosFIUQLaM8=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:42 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:lhOQ51Hc3MfoJXoMmosFIUQLaM8=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:42 GMT'), ('content-length', '275'), ('x-amz-request-id', 'tx000000000000000000408-0057f57e5e-1021-default'), ('content-type', 'application/xml')]
boto: DEBUG: <?xml version="1.0" encoding="UTF-8"?><InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>rzarzynski-idqx3zorqinxhcpn6a-249</Bucket><Key>mymultipart</Key><UploadId>2~6B4ohhO1ZLthBoyAuKlnLmFt5oDonMM</UploadId></InitiateMultipartUploadResult>
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart?uploadId=2~6B4ohhO1ZLthBoyAuKlnLmFt5oDonMM&partNumber=1
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart?uploadId=2~6B4ohhO1ZLthBoyAuKlnLmFt5oDonMM&partNumber=1
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart?uploadId=2~6B4ohhO1ZLthBoyAuKlnLmFt5oDonMM&partNumber=1
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '5242880', 'Content-MD5': u'XztdVV1MtMWmR9Ns59NEoQ==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
XztdVV1MtMWmR9Ns59NEoQ==
application/octet-stream
Wed, 05 Oct 2016 22:27:42 GMT
/rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart?partNumber=1&uploadId=2~6B4ohhO1ZLthBoyAuKlnLmFt5oDonMM
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:5VE+jCqkw3chF9O7enhK002g+VY=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'XztdVV1MtMWmR9Ns59NEoQ==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:42 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:5VE+jCqkw3chF9O7enhK002g+VY='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
XztdVV1MtMWmR9Ns59NEoQ==
application/octet-stream
Wed, 05 Oct 2016 22:27:42 GMT
/rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart?partNumber=1&uploadId=2~6B4ohhO1ZLthBoyAuKlnLmFt5oDonMM
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:5VE+jCqkw3chF9O7enhK002g+VY=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'XztdVV1MtMWmR9Ns59NEoQ==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:42 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:5VE+jCqkw3chF9O7enhK002g+VY='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
XztdVV1MtMWmR9Ns59NEoQ==
application/octet-stream
Wed, 05 Oct 2016 22:27:42 GMT
/rzarzynski-idqx3zorqinxhcpn6a-249/mymultipart?partNumber=1&uploadId=2~6B4ohhO1ZLthBoyAuKlnLmFt5oDonMM
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:5VE+jCqkw3chF9O7enhK002g+VY=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'XztdVV1MtMWmR9Ns59NEoQ==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:42 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:5VE+jCqkw3chF9O7enhK002g+VY='}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_multipart_upload_overwrite_existing_object
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4793, in test_multipart_upload_overwrite_existing_object
    key.set_contents_from_string(payload)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1426, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-250/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-250/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-250/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:27:43 GMT
/rzarzynski-idqx3zorqinxhcpn6a-250/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:lC/GKeW3U3KPDGi5h0ckxDmq+t8=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:43 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:lC/GKeW3U3KPDGi5h0ckxDmq+t8=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:43 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000409-0057f57e5f-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-250/mymultipart
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-250/mymultipart
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-250/mymultipart
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '5242880', 'Content-MD5': u'nsmJ9+x6kTPiAyMMU5b0gA==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
nsmJ9+x6kTPiAyMMU5b0gA==
application/octet-stream
Wed, 05 Oct 2016 22:27:43 GMT
/rzarzynski-idqx3zorqinxhcpn6a-250/mymultipart
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:rVnipiV8fGJL+ttl21e4j9vA6nU=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'nsmJ9+x6kTPiAyMMU5b0gA==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:43 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:rVnipiV8fGJL+ttl21e4j9vA6nU='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
nsmJ9+x6kTPiAyMMU5b0gA==
application/octet-stream
Wed, 05 Oct 2016 22:27:43 GMT
/rzarzynski-idqx3zorqinxhcpn6a-250/mymultipart
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:rVnipiV8fGJL+ttl21e4j9vA6nU=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'nsmJ9+x6kTPiAyMMU5b0gA==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:43 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:rVnipiV8fGJL+ttl21e4j9vA6nU='}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_abort_multipart_upload
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4811, in test_abort_multipart_upload
    (upload, data) = _multipart_upload(bucket, key, 10 * 1024 * 1024)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4612, in _multipart_upload
    transfer_part(bucket, upload.id, upload.key_name, i, part)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4580, in transfer_part
    mp.upload_part_from_file(part_out, i+1)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-251/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-251/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-251/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:27:44 GMT
/rzarzynski-idqx3zorqinxhcpn6a-251/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:BayjquDRHP6q+HpRTl8Nv1sImQI=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:44 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:BayjquDRHP6q+HpRTl8Nv1sImQI=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:44 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx00000000000000000040a-0057f57e60-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart?uploads
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart?uploads
boto: DEBUG: Method: POST
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart?uploads
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST


Wed, 05 Oct 2016 22:27:44 GMT
/rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:mUXdNQ4XrUSJJ4j7dF0rpKamx6E=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:44 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:mUXdNQ4XrUSJJ4j7dF0rpKamx6E=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST


Wed, 05 Oct 2016 22:27:44 GMT
/rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:mUXdNQ4XrUSJJ4j7dF0rpKamx6E=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:44 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:mUXdNQ4XrUSJJ4j7dF0rpKamx6E=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:44 GMT'), ('content-length', '275'), ('x-amz-request-id', 'tx00000000000000000040b-0057f57e60-1021-default'), ('content-type', 'application/xml')]
boto: DEBUG: <?xml version="1.0" encoding="UTF-8"?><InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>rzarzynski-idqx3zorqinxhcpn6a-251</Bucket><Key>mymultipart</Key><UploadId>2~AsoQy4u2tWIBkdrjdY5SowyfH4dy25L</UploadId></InitiateMultipartUploadResult>
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart?uploadId=2~AsoQy4u2tWIBkdrjdY5SowyfH4dy25L&partNumber=1
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart?uploadId=2~AsoQy4u2tWIBkdrjdY5SowyfH4dy25L&partNumber=1
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart?uploadId=2~AsoQy4u2tWIBkdrjdY5SowyfH4dy25L&partNumber=1
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '5242880', 'Content-MD5': u'GTlb1/dKGkPsJ3KPCMsh9w==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
GTlb1/dKGkPsJ3KPCMsh9w==
application/octet-stream
Wed, 05 Oct 2016 22:27:44 GMT
/rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart?partNumber=1&uploadId=2~AsoQy4u2tWIBkdrjdY5SowyfH4dy25L
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:CdW1lsG1n8ayTe6mLa4OOK0iMvE=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'GTlb1/dKGkPsJ3KPCMsh9w==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:44 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:CdW1lsG1n8ayTe6mLa4OOK0iMvE='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
GTlb1/dKGkPsJ3KPCMsh9w==
application/octet-stream
Wed, 05 Oct 2016 22:27:44 GMT
/rzarzynski-idqx3zorqinxhcpn6a-251/mymultipart?partNumber=1&uploadId=2~AsoQy4u2tWIBkdrjdY5SowyfH4dy25L
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:CdW1lsG1n8ayTe6mLa4OOK0iMvE=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'GTlb1/dKGkPsJ3KPCMsh9w==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:44 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:CdW1lsG1n8ayTe6mLa4OOK0iMvE='}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_list_multipart_upload
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4835, in test_list_multipart_upload
    (upload1, data) = _multipart_upload(bucket, key, 5 * mb, do_list = True)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4612, in _multipart_upload
    transfer_part(bucket, upload.id, upload.key_name, i, part)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4580, in transfer_part
    mp.upload_part_from_file(part_out, i+1)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-253/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-253/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-253/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:27:45 GMT
/rzarzynski-idqx3zorqinxhcpn6a-253/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:nHKx2W/IqajtwLvGqdCE2lpAlIU=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:45 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:nHKx2W/IqajtwLvGqdCE2lpAlIU=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:27:45 GMT
/rzarzynski-idqx3zorqinxhcpn6a-253/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:nHKx2W/IqajtwLvGqdCE2lpAlIU=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:45 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:nHKx2W/IqajtwLvGqdCE2lpAlIU=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:46 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx00000000000000000040e-0057f57e62-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart?uploads
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart?uploads
boto: DEBUG: Method: POST
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart?uploads
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST


Wed, 05 Oct 2016 22:27:46 GMT
/rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:8vC4dVs8SQ5MRQnS5077giYK4Sg=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:46 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:8vC4dVs8SQ5MRQnS5077giYK4Sg=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST


Wed, 05 Oct 2016 22:27:46 GMT
/rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:8vC4dVs8SQ5MRQnS5077giYK4Sg=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:46 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:8vC4dVs8SQ5MRQnS5077giYK4Sg=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:47 GMT'), ('content-length', '275'), ('x-amz-request-id', 'tx00000000000000000040f-0057f57e63-1021-default'), ('content-type', 'application/xml')]
boto: DEBUG: <?xml version="1.0" encoding="UTF-8"?><InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>rzarzynski-idqx3zorqinxhcpn6a-253</Bucket><Key>mymultipart</Key><UploadId>2~hufJwuaEAtu-6blaRyYlc3enmP9vjhr</UploadId></InitiateMultipartUploadResult>
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart?uploadId=2~hufJwuaEAtu-6blaRyYlc3enmP9vjhr&partNumber=1
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart?uploadId=2~hufJwuaEAtu-6blaRyYlc3enmP9vjhr&partNumber=1
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart?uploadId=2~hufJwuaEAtu-6blaRyYlc3enmP9vjhr&partNumber=1
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '5242880', 'Content-MD5': u'j503GnfeYKt+qbPKLwrStA==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
j503GnfeYKt+qbPKLwrStA==
application/octet-stream
Wed, 05 Oct 2016 22:27:47 GMT
/rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart?partNumber=1&uploadId=2~hufJwuaEAtu-6blaRyYlc3enmP9vjhr
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:IagM9h961uHBTYY7ISj3i7yRJWg=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'j503GnfeYKt+qbPKLwrStA==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:47 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:IagM9h961uHBTYY7ISj3i7yRJWg='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
j503GnfeYKt+qbPKLwrStA==
application/octet-stream
Wed, 05 Oct 2016 22:27:47 GMT
/rzarzynski-idqx3zorqinxhcpn6a-253/mymultipart?partNumber=1&uploadId=2~hufJwuaEAtu-6blaRyYlc3enmP9vjhr
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:IagM9h961uHBTYY7ISj3i7yRJWg=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'j503GnfeYKt+qbPKLwrStA==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:27:47 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:IagM9h961uHBTYY7ISj3i7yRJWg='}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_100_continue
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4928, in test_100_continue
    status = _simple_http_req_100_cont(s3.main.host, s3.main.port, s3.main.is_secure, 'PUT', resource)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4911, in _simple_http_req_100_cont
    l = data.split(' ')
UnboundLocalError: local variable 'data' referenced before assignment
-------------------- >> begin captured stdout << ---------------------
got response:  timed out
most likely server doesn't support 100-continue

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-256/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-256/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-256/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:27:51 GMT
/rzarzynski-idqx3zorqinxhcpn6a-256/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:ruXGrx8x3xnYuEIlgCUSS3Nh3Aw=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:51 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:ruXGrx8x3xnYuEIlgCUSS3Nh3Aw=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:27:51 GMT
/rzarzynski-idqx3zorqinxhcpn6a-256/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:ruXGrx8x3xnYuEIlgCUSS3Nh3Aw=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:27:51 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:ruXGrx8x3xnYuEIlgCUSS3Nh3Aw=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:27:52 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx00000000000000000041a-0057f57e68-1021-default')]
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_atomic_read_8mb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 5214, in test_atomic_read_8mb
    _test_atomic_read(1024*1024*8)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 5171, in _test_atomic_read
    key.set_contents_from_file(fp_a)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-263/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-263/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-263/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:29:06 GMT
/rzarzynski-idqx3zorqinxhcpn6a-263/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:vS9RKrhqacTTKRQD/PQatBjdWHs=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:29:06 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:vS9RKrhqacTTKRQD/PQatBjdWHs=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:29:06 GMT
/rzarzynski-idqx3zorqinxhcpn6a-263/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:vS9RKrhqacTTKRQD/PQatBjdWHs=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:29:06 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:vS9RKrhqacTTKRQD/PQatBjdWHs=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:29:07 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx0000000000000000004c4-0057f57eb3-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-263/testobj
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-263/testobj
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-263/testobj
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '8388608', 'Content-MD5': u'UYiGy3DBwRnJmtG7tYZeeg==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
UYiGy3DBwRnJmtG7tYZeeg==
application/octet-stream
Wed, 05 Oct 2016 22:29:07 GMT
/rzarzynski-idqx3zorqinxhcpn6a-263/testobj
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:ByVWrAtOPjRxc3MMkguD8DmndGs=
boto: DEBUG: Final headers: {'Content-Length': '8388608', 'Content-MD5': 'UYiGy3DBwRnJmtG7tYZeeg==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:29:07 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:ByVWrAtOPjRxc3MMkguD8DmndGs='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
UYiGy3DBwRnJmtG7tYZeeg==
application/octet-stream
Wed, 05 Oct 2016 22:29:07 GMT
/rzarzynski-idqx3zorqinxhcpn6a-263/testobj
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:ByVWrAtOPjRxc3MMkguD8DmndGs=
boto: DEBUG: Final headers: {'Content-Length': '8388608', 'Content-MD5': 'UYiGy3DBwRnJmtG7tYZeeg==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:29:07 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:ByVWrAtOPjRxc3MMkguD8DmndGs='}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_atomic_write_8mb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 5266, in test_atomic_write_8mb
    _test_atomic_write(1024*1024*8)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 5230, in _test_atomic_write
    key.set_contents_from_file(fp_a)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-266/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-266/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-266/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:29:15 GMT
/rzarzynski-idqx3zorqinxhcpn6a-266/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:9bNLlInDHTCyORJKHF1/NQJh6IM=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:29:15 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:9bNLlInDHTCyORJKHF1/NQJh6IM=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:29:15 GMT
/rzarzynski-idqx3zorqinxhcpn6a-266/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:9bNLlInDHTCyORJKHF1/NQJh6IM=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:29:15 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:9bNLlInDHTCyORJKHF1/NQJh6IM=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:29:16 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx0000000000000000004d5-0057f57ebc-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-266/testobj
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-266/testobj
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-266/testobj
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '8388608', 'Content-MD5': u'UYiGy3DBwRnJmtG7tYZeeg==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
UYiGy3DBwRnJmtG7tYZeeg==
application/octet-stream
Wed, 05 Oct 2016 22:29:16 GMT
/rzarzynski-idqx3zorqinxhcpn6a-266/testobj
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:nKKqMb+zOVyVSwdnKzSKRE+RKn4=
boto: DEBUG: Final headers: {'Content-Length': '8388608', 'Content-MD5': 'UYiGy3DBwRnJmtG7tYZeeg==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:29:16 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:nKKqMb+zOVyVSwdnKzSKRE+RKn4='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
UYiGy3DBwRnJmtG7tYZeeg==
application/octet-stream
Wed, 05 Oct 2016 22:29:16 GMT
/rzarzynski-idqx3zorqinxhcpn6a-266/testobj
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:nKKqMb+zOVyVSwdnKzSKRE+RKn4=
boto: DEBUG: Final headers: {'Content-Length': '8388608', 'Content-MD5': 'UYiGy3DBwRnJmtG7tYZeeg==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:29:16 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:nKKqMb+zOVyVSwdnKzSKRE+RKn4='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
UYiGy3DBwRnJmtG7tYZeeg==
application/octet-stream
Wed, 05 Oct 2016 22:29:16 GMT
/rzarzynski-idqx3zorqinxhcpn6a-266/testobj
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:nKKqMb+zOVyVSwdnKzSKRE+RKn4=
boto: DEBUG: Final headers: {'Content-Length': '8388608', 'Content-MD5': 'UYiGy3DBwRnJmtG7tYZeeg==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:29:16 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:nKKqMb+zOVyVSwdnKzSKRE+RKn4='}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_atomic_dual_write_8mb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 5311, in test_atomic_dual_write_8mb
    _test_atomic_dual_write(1024*1024*8)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 5287, in _test_atomic_dual_write
    key.set_contents_from_file(fp_b)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1269, in set_contents_from_file
    md5 = self.compute_md5(fp, size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1020, in compute_md5
    hex_digest, b64_digest, data_size = compute_md5(fp, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/utils.py", line 991, in compute_md5
    return compute_hash(fp, buf_size, size, hash_algorithm=md5)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/utils.py", line 1012, in compute_hash
    s = fp.read(buf_size)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 5108, in read
    self.interrupt()
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 5285, in <lambda>
    lambda: key2.set_contents_from_file(fp_a, rewind=True)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-269/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-269/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-269/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:29:24 GMT
/rzarzynski-idqx3zorqinxhcpn6a-269/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:Jkpnsr0XWQsssLR0+e2MSed2NIc=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:29:24 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:Jkpnsr0XWQsssLR0+e2MSed2NIc=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:29:24 GMT
/rzarzynski-idqx3zorqinxhcpn6a-269/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:Jkpnsr0XWQsssLR0+e2MSed2NIc=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:29:24 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:Jkpnsr0XWQsssLR0+e2MSed2NIc=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:29:25 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx0000000000000000004e0-0057f57ec5-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-269/testobj
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-269/testobj
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-269/testobj
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '8388608', 'Content-MD5': u'UYiGy3DBwRnJmtG7tYZeeg==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
UYiGy3DBwRnJmtG7tYZeeg==
application/octet-stream
Wed, 05 Oct 2016 22:29:25 GMT
/rzarzynski-idqx3zorqinxhcpn6a-269/testobj
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:WE+dqivkTYYY0vvWp+M/CCARA1A=
boto: DEBUG: Final headers: {'Content-Length': '8388608', 'Content-MD5': 'UYiGy3DBwRnJmtG7tYZeeg==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:29:25 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:WE+dqivkTYYY0vvWp+M/CCARA1A='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
UYiGy3DBwRnJmtG7tYZeeg==
application/octet-stream
Wed, 05 Oct 2016 22:29:25 GMT
/rzarzynski-idqx3zorqinxhcpn6a-269/testobj
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:WE+dqivkTYYY0vvWp+M/CCARA1A=
boto: DEBUG: Final headers: {'Content-Length': '8388608', 'Content-MD5': 'UYiGy3DBwRnJmtG7tYZeeg==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:29:25 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:WE+dqivkTYYY0vvWp+M/CCARA1A='}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: s3tests.functional.test_s3.test_versioning_obj_create_overwrite_multipart
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 6025, in test_versioning_obj_create_overwrite_multipart
    c.append(_do_test_multipart_upload_contents(bucket, objname, 3))
  File "/work/s3-tests/s3tests/functional/test_s3.py", line 4758, in _do_test_multipart_upload_contents
    mp.upload_part_from_file(StringIO(payload), i+1)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request

-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-284/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-284/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-284/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:43:43 GMT
/rzarzynski-idqx3zorqinxhcpn6a-284/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:kpO7jcJEqIziQp05b+6M2GSTQr4=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:43:43 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:kpO7jcJEqIziQp05b+6M2GSTQr4=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:43:43 GMT
/rzarzynski-idqx3zorqinxhcpn6a-284/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:kpO7jcJEqIziQp05b+6M2GSTQr4=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:43:43 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:kpO7jcJEqIziQp05b+6M2GSTQr4=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:43:43 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000b54-0057f5821f-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-284/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-284/
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-284/?versioning
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-284/?versioning
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-284/?versioning
boto: DEBUG: Data: <?xml version="1.0" encoding="UTF-8"?>
       <VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
         <Status>Enabled</Status>
         <MfaDelete>Disabled</MfaDelete>
       </VersioningConfiguration>
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:43:43 GMT
/rzarzynski-idqx3zorqinxhcpn6a-284/?versioning
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:ONHNrflGsdwCATeHbZdbDLjRWyM=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:43:43 GMT', 'Content-Length': '228', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:ONHNrflGsdwCATeHbZdbDLjRWyM=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:43:43 GMT
/rzarzynski-idqx3zorqinxhcpn6a-284/?versioning
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:ONHNrflGsdwCATeHbZdbDLjRWyM=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:43:43 GMT', 'Content-Length': '228', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:ONHNrflGsdwCATeHbZdbDLjRWyM=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:43:43 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000b55-0057f5821f-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-284/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-284/
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-284/?versioning
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-284/?versioning
boto: DEBUG: Method: GET
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-284/?versioning
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
GET


Wed, 05 Oct 2016 22:43:43 GMT
/rzarzynski-idqx3zorqinxhcpn6a-284/?versioning
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:asWCnxVhBkUt7t5BSQaSRZs6+VY=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:43:43 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:asWCnxVhBkUt7t5BSQaSRZs6+VY=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
GET


Wed, 05 Oct 2016 22:43:43 GMT
/rzarzynski-idqx3zorqinxhcpn6a-284/?versioning
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:asWCnxVhBkUt7t5BSQaSRZs6+VY=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:43:43 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:asWCnxVhBkUt7t5BSQaSRZs6+VY=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:43:44 GMT'), ('content-length', '161'), ('x-amz-request-id', 'tx000000000000000000b56-0057f58220-1021-default'), ('content-type', 'application/xml')]
boto: DEBUG: <?xml version="1.0" encoding="UTF-8"?><VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Status>Enabled</Status></VersioningConfiguration>
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-284/testobj
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-284/testobj
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-284/testobj?uploads
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-284/testobj?uploads
boto: DEBUG: Method: POST
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-284/testobj?uploads
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST


Wed, 05 Oct 2016 22:43:44 GMT
/rzarzynski-idqx3zorqinxhcpn6a-284/testobj?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:JbQPS8C/iB8Zf1N6tvrT9Zrw0QE=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:43:44 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:JbQPS8C/iB8Zf1N6tvrT9Zrw0QE=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
POST


Wed, 05 Oct 2016 22:43:44 GMT
/rzarzynski-idqx3zorqinxhcpn6a-284/testobj?uploads
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:JbQPS8C/iB8Zf1N6tvrT9Zrw0QE=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:43:44 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:JbQPS8C/iB8Zf1N6tvrT9Zrw0QE=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:43:45 GMT'), ('content-length', '271'), ('x-amz-request-id', 'tx000000000000000000b57-0057f58221-1021-default'), ('content-type', 'application/xml')]
boto: DEBUG: <?xml version="1.0" encoding="UTF-8"?><InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>rzarzynski-idqx3zorqinxhcpn6a-284</Bucket><Key>testobj</Key><UploadId>2~1qOjJwiC5hG2K1yt1mK6KmTSAC1gqYA</UploadId></InitiateMultipartUploadResult>
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-284/testobj
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-284/testobj
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-284/testobj?uploadId=2~1qOjJwiC5hG2K1yt1mK6KmTSAC1gqYA&partNumber=1
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-284/testobj?uploadId=2~1qOjJwiC5hG2K1yt1mK6KmTSAC1gqYA&partNumber=1
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-284/testobj?uploadId=2~1qOjJwiC5hG2K1yt1mK6KmTSAC1gqYA&partNumber=1
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '5242880', 'Content-MD5': u'W+qRL2plCABYUSgmXqs/Fw==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
W+qRL2plCABYUSgmXqs/Fw==
application/octet-stream
Wed, 05 Oct 2016 22:43:45 GMT
/rzarzynski-idqx3zorqinxhcpn6a-284/testobj?partNumber=1&uploadId=2~1qOjJwiC5hG2K1yt1mK6KmTSAC1gqYA
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:d+Pg5z1i8tqahQACMmpcWjjH5XY=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'W+qRL2plCABYUSgmXqs/Fw==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:43:45 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:d+Pg5z1i8tqahQACMmpcWjjH5XY='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
W+qRL2plCABYUSgmXqs/Fw==
application/octet-stream
Wed, 05 Oct 2016 22:43:45 GMT
/rzarzynski-idqx3zorqinxhcpn6a-284/testobj?partNumber=1&uploadId=2~1qOjJwiC5hG2K1yt1mK6KmTSAC1gqYA
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:d+Pg5z1i8tqahQACMmpcWjjH5XY=
boto: DEBUG: Final headers: {'Content-Length': '5242880', 'Content-MD5': 'W+qRL2plCABYUSgmXqs/Fw==', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:43:45 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:d+Pg5z1i8tqahQACMmpcWjjH5XY='}
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: s3tests.functional.test_headers.test_object_create_bad_md5_unreadable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_headers.py", line 230, in test_object_create_bad_md5_unreadable
    eq(e.status, 403)
AssertionError: 400 != 403
-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-5/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-5/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-5/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:19:30 GMT
/rzarzynski-idqx3zorqinxhcpn6a-5/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:o1aj1bgpynbpk6BKq0uaKv/kTyM=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:19:30 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:o1aj1bgpynbpk6BKq0uaKv/kTyM=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:19:30 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx00000000000000000000c-0057f57c72-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-5/foo
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-5/foo
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-5/foo
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '3', 'Content-MD5': u'N7UdGUp1E+RbVvZSTy1R8g==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT

application/octet-stream
Wed, 05 Oct 2016 22:19:30 GMT
/rzarzynski-idqx3zorqinxhcpn6a-5/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:LmC/jcYluXg4fUxxSd1qNTM9/1Y=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:19:30 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:LmC/jcYluXg4fUxxSd1qNTM9/1Y=', 'Content-MD5': '\x07'}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT

application/octet-stream
Wed, 05 Oct 2016 22:19:30 GMT
/rzarzynski-idqx3zorqinxhcpn6a-5/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:LmC/jcYluXg4fUxxSd1qNTM9/1Y=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': 'Wed, 05 Oct 2016 22:19:30 GMT', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:LmC/jcYluXg4fUxxSd1qNTM9/1Y=', 'Content-MD5': '\x07'}
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: s3tests.functional.test_headers.test_object_create_bad_date_unreadable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_headers.py", line 574, in test_object_create_bad_date_unreadable
    eq(e.status, 403)
AssertionError: 400 != 403
-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-25/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-25/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-25/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 05 Oct 2016 22:19:46 GMT
/rzarzynski-idqx3zorqinxhcpn6a-25/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:NGLqteTcEtuVgKMH7YnfkE9veKg=
boto: DEBUG: Final headers: {'Date': 'Wed, 05 Oct 2016 22:19:46 GMT', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:NGLqteTcEtuVgKMH7YnfkE9veKg=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('date', 'Wed, 05 Oct 2016 22:19:46 GMT'), ('content-length', '0'), ('x-amz-request-id', 'tx000000000000000000030-0057f57c82-1021-default')]
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-25/foo
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-25/foo
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-25/foo
boto: DEBUG: Data: 
boto: DEBUG: Headers: {'Content-Length': '3', 'Content-MD5': u'N7UdGUp1E+RbVvZSTy1R8g==', 'Content-Type': 'application/octet-stream', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream

/rzarzynski-idqx3zorqinxhcpn6a-25/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:CnLjuWw4m4G4sQtlu2d+n/iosvs=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': '\x07', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:CnLjuWw4m4G4sQtlu2d+n/iosvs=', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g=='}
boto: DEBUG: encountered error exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT
N7UdGUp1E+RbVvZSTy1R8g==
application/octet-stream

/rzarzynski-idqx3zorqinxhcpn6a-25/foo
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:CnLjuWw4m4G4sQtlu2d+n/iosvs=
boto: DEBUG: Final headers: {'Content-Length': '3', 'Expect': '100-Continue', 'Date': '\x07', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:CnLjuWw4m4G4sQtlu2d+n/iosvs=', 'Content-MD5': 'N7UdGUp1E+RbVvZSTy1R8g=='}
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: s3tests.functional.test_headers.test_bucket_create_bad_date_unreadable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/s3-tests/s3tests/functional/test_headers.py", line 913, in test_bucket_create_bad_date_unreadable
    eq(e.status, 403)
AssertionError: 400 != 403
-------------------- >> begin captured logging << --------------------
boto: DEBUG: path=/rzarzynski-idqx3zorqinxhcpn6a-46/
boto: DEBUG: auth_path=/rzarzynski-idqx3zorqinxhcpn6a-46/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /rzarzynski-idqx3zorqinxhcpn6a-46/
boto: DEBUG: Data: 
boto: DEBUG: Headers: {}
boto: DEBUG: Host: localhost:8000
boto: DEBUG: Port: 8000
boto: DEBUG: Params: {}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT



/rzarzynski-idqx3zorqinxhcpn6a-46/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:l1/twtj/g0fcVnlwHBDq+KynCho=
boto: DEBUG: Final headers: {'Date': '\x07', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:l1/twtj/g0fcVnlwHBDq+KynCho=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'port': 8000, 'timeout': 70}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT



/rzarzynski-idqx3zorqinxhcpn6a-46/
boto: DEBUG: Signature:
AWS f05e187d8d4f43a7972b03a92681194a:l1/twtj/g0fcVnlwHBDq+KynCho=
boto: DEBUG: Final headers: {'Date': '\x07', 'Content-Length': '0', 'Authorization': u'AWS f05e187d8d4f43a7972b03a92681194a:l1/twtj/g0fcVnlwHBDq+KynCho=', 'User-Agent': 'Boto/2.38.0 Python/2.7.6 Linux/3.19.0-25-generic'}
boto: DEBUG: Response headers: [('content-length', '0')]
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 346 tests in 1550.933s

FAILED (SKIP=4, errors=22, failures=3)
